import {
  Building2,
  Brush,
  Home,
  Layers,
  Paintbrush,
  Sparkles,
  Star,
  Waves,
} from "lucide-react";

export const navItems = [
  { href: "/", label: "Home" },
  { href: "/services", label: "Services" },
  { href: "/projects", label: "Projects" },
  { href: "/painting-gallery", label: "Gallery" },
  { href: "/painting-tips", label: "Painting Tips" },
  { href: "/reviews", label: "Reviews" },
  { href: "/contact", label: "Contact" },
];

export const services = [
  {
    title: "Residential Painting",
    href: "/services#residential-painting",
    icon: Home,
    summary: "Neat, durable finishes for Sydney homes, apartments, units, and renovations.",
  },
  {
    title: "Interior Painting",
    href: "/services#interior-painting",
    icon: Paintbrush,
    summary: "Walls, trims, doors, ceilings, feature walls, and full interior refreshes.",
  },
  {
    title: "Exterior Painting",
    href: "/services#exterior-painting",
    icon: Brush,
    summary: "Weather-conscious preparation and coating for facades, fences, eaves, and decks.",
  },
  {
    title: "Strata Painting",
    href: "/services#strata-painting",
    icon: Layers,
    summary: "Common areas, lobbies, stairwells, corridors, and planned maintenance painting.",
  },
  {
    title: "Commercial Painting",
    href: "/services#commercial-painting",
    icon: Building2,
    summary: "Professional painting for offices, retail spaces, hospitality venues, and fit-outs.",
  },
  {
    title: "Ceiling Repainting",
    href: "/services#ceiling-repainting",
    icon: Sparkles,
    summary: "Clean ceiling repaints, stain blocking, patching, and smooth finish restoration.",
  },
  {
    title: "Mould-Damaged Ceiling Restoration",
    href: "/services#mould-damaged-ceiling-restoration",
    icon: Waves,
    summary: "Careful preparation and repainting for ceilings affected by moisture and mould damage.",
  },
];

export const projects = [
  {
    title: "Interior Repaint",
    location: "Sydney apartment",
    before: "Tired walls, scuffed trims, uneven ceiling colour.",
    after: "Soft neutral walls, crisp trims, brighter rooms.",
  },
  {
    title: "Exterior Refresh",
    location: "Suburban home",
    before: "Weathered facade and faded timber details.",
    after: "Fresh exterior palette with clean, durable finish.",
  },
  {
    title: "Ceiling Restoration",
    location: "Moisture-affected room",
    before: "Stained ceiling with patchy surface damage.",
    after: "Prepared, sealed, and repainted ceiling finish.",
  },
];

export const reviews = [
  {
    name: "lendy Lin",
    rating: 5,
    quote:
      "Caleb and his team did a great job for painting my whole house. His team is efficient, professional and reliable. Caleb is easy to communicate. I am very happy with his service and all the work he has done. I highly recommend F&S Painting, thank you Caleb and team.",
  },
  {
    name: "anne nicholson",
    rating: 5,
    quote:
      "This is the second time we have used F&S Painting Services in the past 2 years. First time was for the unit in which we live and second time, just recently, was for a little investment unit. We couldn't be happier with the results. Caleb was a pleasure to deal with. the painting was exceptional with absolutely no mess. He was prompt and efficient and we have absolutely no hesitation in recommending him. Thanks Caleb for the great job!",
  },
  {
    name: "Joanna Santos",
    rating: 5,
    quote:
      "Caleb was an absolute professional. He's work is of very high quality and I highly recommend his service. Will definitely use services again.",
  },
  {
    name: "Kenneth Tse",
    rating: 5,
    quote:
      "I had Caleb and his team come paint my 2 story brick home over several weeks. They painted both inside and outside and did a fantastic job. They were very thorough and detailed in the job and we were very happy with the results. Would highly recommend them for any painting job. We are even getting them to come back again and paint our kitchen cabinets. Thank you Caleb and his team.",
  },
  {
    name: "Won College",
    rating: 5,
    quote:
      "We would like to extend a huge thank you to Caleb and his team for their exceptional service and professionalism during the entire process of painting the interior and exterior of our property. Amazing team filled with genuine people! Throughout the job, the team was always on time, providing constant updates on the process of the job and giving expert advice derived from their extensive experience in the field! Will definitely be calling them up again for any of our future painting jobs!",
  },
  {
    name: "jan churcher",
    rating: 5,
    quote:
      "Efficient, professional thorough service. They arrived promptly, did a great job and cleaned up very well. Excellent job",
  },
];

export const tips = [
  {
    slug: "house-painting-cost-sydney",
    title: "How Much Does House Painting Cost in Sydney?",
    excerpt: "What affects house painting costs in Sydney and how to prepare for a clearer quote.",
    readTime: "4 min read",
  },
  {
    slug: "best-paint-finish-interior-walls-sydney",
    title: "Best Paint Finish for Interior Walls in Sydney Homes",
    excerpt: "A practical guide to choosing matte, low sheen, or washable finishes for interior walls.",
    readTime: "3 min read",
  },
  {
    slug: "fix-mould-damaged-ceilings-before-painting",
    title: "How to Fix Mould-Damaged Ceilings Before Painting",
    excerpt: "What should happen before repainting a mould-affected ceiling and why moisture must be resolved first.",
    readTime: "5 min read",
  },
];

export const serviceAreas = [
  "Eastern Suburbs",
  "Greater Western Sydney",
  "Hills District",
  "Central West",
  "Inner West",
  "Northern Beaches",
  "North Shore",
  "Southern Sydney",
  "St George",
  "South-eastern Sydney",
  "South-western Sydney",
  "Ashfield",
  "Auburn",
  "Bankstown",
  "Baulkham Hills",
  "Blacktown",
  "Botany Bay",
  "Burwood",
  "Camden",
  "Campbelltown",
  "Canada Bay",
  "Canterbury",
  "Fairfield",
  "Holroyd",
  "Hornsby",
  "Hunter's Hill",
  "Hurstville",
  "Kogarah",
  "Ku-ring-gai",
  "Lane Cove",
  "Leichhardt",
  "Liverpool",
  "Manly",
  "Marrickville",
  "Mosman",
  "North Sydney",
  "Parramatta",
  "Penrith",
  "Pittwater",
  "Randwick",
  "Rockdale",
  "Ryde",
  "Strathfield",
  "Sutherland",
  "City of Sydney",
  "Warringah",
  "Waverley",
  "Willoughby",
  "Woollahra",
  "Balmain",
  "Beverly Hills",
  "Bondi",
  "Carlingford",
  "Castle Hill",
  "Cronulla",
  "Crows Nest",
  "Dee Why",
  "Double Bay",
  "Drummoyne",
  "Epping",
  "Five Dock",
  "Gladesville",
  "Glebe",
  "Gordon",
  "Granville",
  "Greenacre",
  "Guildford",
  "Homebush",
  "Hornsby Heights",
  "Kellyville",
  "Kingsford",
  "Lane Cove West",
  "Leichhardt",
  "Lidcombe",
  "Maroubra",
  "Mascot",
  "Merrylands",
  "Neutral Bay",
  "Newtown",
  "North Ryde",
  "Paddington",
  "Panania",
  "Petersham",
  "Potts Point",
  "Pyrmont",
  "Redfern",
  "Roseville",
  "Rozelle",
  "Silverwater",
  "Stanmore",
  "Summer Hill",
  "Surry Hills",
  "Thornleigh",
  "Ultimo",
  "Waterloo",
  "West Pennant Hills",
  "Zetland",
];

export const starIcon = Star;
